### ISSUE TITLE
how do i compile this?

### ISSUE THREAD

**Issue by bwanaaa** [DKLoehr/FractaSketch#2]
I opened the project in Xcode and tried to build but got

```

Showing Recent Messages
:-1: Entry point (start) undefined.  Usually in crt1.o for architecture i386

```

**Comment by DKLoehr** [comment]
This is a very old project of mine -- I haven't come back to it in several years, so I'm afraid I don't have a good sense myself of how to build it. Particularly since I am unfamiliar with macs, and was not as well-versed in software engineering during development of this project. I've uploaded my most recent builds (which are several years old) onto the releases page, so you may be able to use those.

A couple of thoughts: This is meant for desktop computers, not iOS. Also, the code relies on the SFML library, so make sure you have that installed.

**Comment by bwanaaa** [comment]
Thank you for your reply. The windows exe does not run under win10 or any of the compatibility modes. 
I did get the Mac version as well as the original fractasketch to run under basilisk2 , a mac quadra emulator.
